SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+01:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;


INSERT INTO `captions` (`capt`, `repl`) VALUES
('development mode - do not use for dispatching', 'Entwicklermodus - Nicht für Produktiveinsatz nutzen'),
('A', 'R'),
('Off', 'Aus'),
('Add Action', 'Rückmeldung'),
('Add Facility', 'Neues Objekt'),
('Add note', 'Notiz'),
('Add Unit', 'Neue Einheit'),
('Add user', 'Neues Benutzerkonto'),
('Add to log', 'In Einsatztagebuch übernehmen'),
('Add to ticket-log', 'In Einsatz-Protokoll übernehmen'),
('Addr', 'Adresse'),
('Additional receiver', 'Weitere Empfänger'),
('Admin permission', 'Administration'),
('Admin and superadmin', 'Schichtführer und Administrator'),
('Alarm audio files', 'Hinweistöne'),
('and additional', 'und Weitere'),
('All selected', 'Alle'),
('As of', 'Stand'),
('Application Interface', 'Anwendungsschnittstelle'),
('Application Interface phone', 'Anwendungsschnittstelle Mobiltelefon'),
('Application Interface - No Login possible', 'Anwendungsschnittstelle - Anmelden nicht möglich.'),
('API-Code', 'API-Code'),
('API settings updated', 'Anwendungsschnittstelle - Einstellungen gespeichert'),
('API connected', 'API verbunden'),
('API disconnected', 'API getrennt'),
('API device-text', 'API Gerätestatus'),
('Associated data service address multiple', 'Datendienst-Adresse mehrfach konfiguriert'),
('Auto-logout disabled', 'Auto-Abmelden abgeschaltet'),
('Auto-logout in', 'Abmelden in'),
('Auto-logout off', 'Auto-Abmelden aus'),
('Available since', 'Verbunden seit'),
('Board', 'Zeiten'),
('Callback phone', 'Rückruf-Nummer'),
('Cancel', 'Abbrechen'),
('Capability', 'Ausstattung'),
('Characters left', 'Verbleibende Zeichen'),
('City', 'PLZ, Ort'),
('Clear', 'Frei(1)'),
('Click to edit.', 'Zum Bearbeiten anklicken.'),
('Close incident', 'Einsatz schließen'),
('Close_incident_short', 'Abschließen'),
('Configuration', 'Einstellungen'),
('Connection test', 'Verbindungstest'),
('Contact email', 'Verwaltung, E-Mail'),
('Contact name', 'Ansprechpartner'),
('Contact phone', 'Verwaltung, Telefon'),
('Current situation', 'Lageübersicht'),
('Current radio', 'Funkkreis'),
('Date of birth', 'Geburtsdatum'),
('Description', 'Beschreibung'),
('Dispatch to ticket - Select ticket', 'Einheit disponieren - Einsatz auswählen'),
('Dispatch Units', 'Einheiten disponieren'),
('Dispatch_Units_short', 'Disponieren'),
('Dispatched', 'Disponiert'),
('Dispo-info', 'Dispo-Info'),
('Edit My Profile', 'Eigenes Konto'),
('Edit Settings', 'Allgemeine Einstellungen'),
('Email users', 'E-Mail an Benutzer');

INSERT INTO `captions` (`capt`, `repl`) VALUES
('_api_setting', 'Variable'),
('_api_encoding', 'Wert'),
('_api_status', 'Status'),
('_api_action', 'Aktion'),
('_api_message_text', 'Text'),
('_api_user_id', 'API-Empfang Benutzer'),
('_api_hosts', 'API-Empfang URL'),
('_api_destination_host', 'API-Versand URL'),
('_api_phone_host', 'API-Versand Mobiltelefon'),
('_api_destination_password', 'API-Versand Passwort'),
('_api_connection_test_configuration', 'API-Test Konfiguration'),
('_api_prefix_phone_encdg', 'API-Präfix Mobiltelefon'),
('_api_prefix_phone_capt', 'Beschriftung Mobiltelefon'),
('_api_prefix_printer_encdg', 'API-Präfix Alarmdrucker'),
('_api_prefix_printer_capt', 'Beschriftung Alarmdrucker'),
('_api_prefix_reporting_channel_1_encdg', 'API-Präfix Meldeweg 1'),
('_api_prefix_reporting_channel_1_capt', 'Beschriftung Meldeweg 1'),
('_api_prefix_reporting_channel_1_regexp', 'Suchmuster Meldeweg 1'),
('_api_prefix_reporting_channel_2_encdg', 'API-Präfix Meldeweg 2'),
('_api_prefix_reporting_channel_2_capt', 'Beschriftung Meldeweg 2'),
('_api_prefix_reporting_channel_2_regexp', 'Suchmuster Meldeweg 2'),
('_api_prefix_reporting_channel_3_encdg', 'API-Präfix Meldeweg 3'),
('_api_prefix_reporting_channel_3_capt', 'Beschriftung Meldeweg 3'),
('_api_prefix_reporting_channel_3_regexp', 'Suchmuster Meldeweg 3'),
('_api_prefix_reporting_channel_4_encdg', 'API-Präfix Meldeweg 4'),
('_api_prefix_reporting_channel_4_capt', 'Beschriftung Meldeweg 4'),
('_api_prefix_reporting_channel_4_regexp', 'Suchmuster Meldeweg 4'),
('_api_prefix_reporting_channel_5_encdg', 'API-Präfix Meldeweg 5'),
('_api_prefix_reporting_channel_5_capt', 'Beschriftung Meldeweg 5'),
('_api_prefix_reporting_channel_5_regexp', 'Suchmuster Meldeweg 5'),
('_api_evaluate_unknown_unit_emergency_encdg', 'Notruf auswerten'),
('_api_disp_encdg', 'Disponiert'),
('_api_resp_encdg', 'Aus(3)'),
('_api_onsc_encdg', 'Ein(4)'),
('_api_fcen_encdg', 'Ab(7)'),
('_api_fcar_encdg', 'An(8)'),
('_api_clr_encdg', 'Frei(1)'),
('_api_quat_encdg', 'Wache(2)'),
('_api_off_duty_encdg', 'Ausser Dienst(6)'),
('_api_callreq_encdg', 'Sprechwunsch(5)'),
('_api_manackn_encdg', 'Handquittung(9)'),
('_api_emgcy_lo_encdg', 'Hilferuf(0)'),
('_api_emgcy_hi_encdg', 'Notruf'),
('_api_ptt_prefix_encdg', 'API-Präfix Sprechtaste'),
('_api_ptt_encdg', 'Sprechtaste'),
('_api_ptt_release_encdg', 'Sprechtaste loslassen'),
('_api_ptt_display_encdg', 'Sprechtaste Anzeigedauer'),
('_api_log_max_display_setng', 'API-Log Anzeigedauer'),
('_api_log_max_age_setng', 'API-Log Speicherdauer'),
('_api_login_logout_setng', 'An- und Abmelden'),
('_api_subscr_unsubscr_setng', 'Teilehmer abonnieren'),
('_api_current_radio_encdg', 'Geschalteter Funkkreis'),
('_api_private_call_encdg', 'Einzelruf'),
('_api_batch_start_stop_setng', 'Stapelübertragung'),
('_api_log_encdg', 'Gerätemeldung'),
('_api_errlog_encdg', 'Fehlermeldung'),
('_api_message_encdg', 'Textnachricht'),
('_api_position_encdg', 'Positionsdaten'),
('_api_default_subject_setng', 'Betreff'),
('_api_dispatch_text_setng', 'Alarmschreiben'),
('_api_dispatch_shorttext_setng', 'Alarmschreiben (kurz)'),
('_api_email_smtp_host', 'E-Mail Server'),
('_api_email_smtp_authentication', 'E-Mail Authentifizierung'),
('_api_email_from', 'E-Mail Absender'),
('_api_email_cc', 'E-Mail Kopie'),
('_api_email_bcc', 'E-Mail Blindkopie'),
('_api_email_reply_to', 'E-Mail Antwort an');

INSERT INTO `captions` (`capt`, `repl`) VALUES
('Guard house', 'Wache'),
('Handle', 'Kurzbezeichnung'),
('High', 'Notfall'),
('ID', 'ID'),
('Incident Lat/Lng', 'Koordinate'),
('Incident dispatch system', 'Incident dispatch system'),
('Incident dispatch system', 'Einsatzleitsystem'),
('Incident name', 'Einsatznummer'),
('Incident types', 'Einsatzstichworte'),
('Incident', 'Einsatz'),
('Tickets', 'Einsätze'),
('Lat/Lng', 'geogr. Länge/Breite'),
('Links', 'Lesezeichen'),
('Incident location', 'Einsatzort'),
('On-Scene location', 'Transportstart'),
('Login', 'Anmelden'),
('Login failed. Username', 'Anmeldung fehlgeschlagen. Benutzername'),
('Logged in', 'Angemeldet'),
('Log-in has expired due to inactivity. Please log in again.', 'Ihre Sitzung ist abgelaufen, bitte loggen Sie sich erneut ein.'),
('Logout', 'Abmelden'),
('Medium', 'Sofort'),
('Mobile', 'Motorisiert'),
('Name', 'Name'),
('Incident type', 'Einsatzstichwort'),
('Incident-types inserted', 'Einsatzstichworte gespeichert'),
('New', 'Neuer Einsatz'),
('Normal', 'Disponibel'),
('o\'clock', 'Uhr'),
('Oldest open disposition. Primary disposition for status reception and acknowledgment via the application interface.', 'Älteste offene Disposition. Primäre Disposition für Statusempfang und -quittung über die Anwendungsschnittstelle.'),
('On-scene', 'Ein(4)'),
('On-scene without ticket', 'Ein(4) ohne Einsatz'),
('Only monitor', 'Beobachten'),
('Opening hours', 'Öffnungszeiten'),
('Optimize Database', 'Optimieren'),
('Password', 'Passwort'),
('Pending updates', 'Verfügbare Versionen'),
('Phone', 'Telefonnummer'),
('Incident Report', 'Einsatzbericht'),
('Position', 'Koordinaten'),
('Direct dialing 1', 'Durchwahl-Nummer 1'),
('Print', 'Drucken'),
('Printed at', 'Gedruckt am'),
('Printer', 'Alarmdrucker'),
('Get printers', 'Drucker suchen'),
('Private Call', 'Einzelruf'),
('Private call requested', 'Einzelruf angefordert'),
('Protocol', 'Alarmvorschlag');

INSERT INTO `captions` (`capt`, `repl`) VALUES
('Release notes', 'Versionshinweise'),
('Reported by', 'Meldender'),
('Reporting channel 1', 'Meldeweg 1'),
('Reporting channel 2', 'Meldeweg 2'),
('Reporting channel 3', 'Meldeweg 3'),
('Reporting channel 4', 'Meldeweg 4'),
('Reporting channel 5', 'Meldeweg 5'),
('Reports', 'Berichte'),
('Reset Database', 'Zurücksetzen'),
('Reset Database functions', 'Datenbank zurücksetzen'),
('Responding', 'Aus(3)'),
('Responding without ticket', 'Aus(3) ohne Einsatz'),
('Run End', 'Einsatzende'),
('Run Start', 'Einsatzbeginn'),
('Scheduled Date', 'Vorbestellt für'),
('Security contact', 'Pförtner, Aufenthalt'),
('Security email', 'Pförtner, E-Mail'),
('Security phone', 'Pförtner, Telefon'),
('Situation', 'Lage'),
('Sort', 'Sortieren nach'),
('St', 'Land'),
('Status', 'Status'),
('Status-Values must be different.', 'Status-Werte müssen unterschiedlich sein.'),
('Superadmin only', 'Nur Administrator'),
('Synopsis', 'Notfallsituation'),
('System', 'System'),
('Type', 'Kategorie'),
('U', 'E'),
('Unit', 'Einheit'),
('Copied', 'Kopiert'),
('Unit name', 'Funkrufname'),
('Unit handle', 'Funk-Code'),
('Units', 'Einheiten'),
('Updated', 'Aktualisiert'),
('Edited', 'Bearbeitet'),
('User', 'Benutzer'),
('Written', 'Angelegt'),
('Window too low for menu!', 'Fenster zu niedrig für Menue!'),
('Cellular phone', 'Mobiltelefon'),
('Dataset in_types updated', 'Datensatz Einsatzstichwort aktualisiert'),
('Dataset textblocks synopsis updated', 'Datensatz Textbaustein-Notfallsituation aktualisiert'),
('Dataset textblocks description updated', 'Datensatz Textbaustein-Bemerkung aktualisiert'),
('Dataset textblocks action updated', 'Datensatz Textbaustein-Rückmeldung aktualisiert'),
('Dataset textblocks assign updated', 'Datensatz Textbaustein-Disposition aktualisiert');

INSERT INTO `captions` (`capt`, `repl`) VALUES
('Dataset textblocks close updated', 'Datensatz Textbaustein-Schlussmeldung aktualisiert'),
('Dataset textblocks log updated', 'Datensatz Textbaustein-Einsatztagebuch aktualisiert'),
('Dataset textblocks message updated', 'Datensatz Textbaustein-Nachrichten aktualisiert'),
('Dataset textblocks fixtext updated', 'Datensatz Fixmeldungen aktualisiert'),
('Dataset fac_types updated', 'Datensatz Objekt-Kategorie aktualisiert'),
('Dataset fac_status updated', 'Datensatz Objekt-Status aktualisiert'),
('Dataset facility updated', 'Datensatz Objekt aktualisiert');

INSERT INTO `captions` (`capt`, `repl`) VALUES
('Dataset unit_types updated', 'Datensatz Einheiten-Konfiguration aktualisiert'),
('Dataset un_status updated', 'Datensatz Einheiten-Status aktualisiert'),
('Dataset unit updated', 'Datensatz Einheiten aktualisiert'),
(' *na*', '*keine*');

INSERT INTO `captions` (`capt`, `repl`) VALUES
(' *not*', '*keiner*'),
('Mouseover for details.', 'Weitere Informationen: Feld mit der Maus überfahren.'),
('[No Address]', '[Kein Einsatzort angegeben]'),
('[No on-scene location]', '[Kein Transportstart angegeben]'),
('[No description]', '[keine Angaben]'),
('[Simulation]', '[Simulation]'),
('Access rules', 'Zugangs-Info'),
('Action', 'Rückmeldung'),
('Action added', 'Rückmeldung zugefügt'),
('Action updated', 'Rückmeldung bearbeitet'),
('Actions', 'Rückmeldungen'),
('ActionDescription is required', 'Rückmeldung'),
('Add new', 'Neu zufügen');

INSERT INTO `captions` (`capt`, `repl`) VALUES
('Address', 'Adresse'),
('Incident Reports', 'Einsatzberichte'),
('age', 'Geöffnet seit'),
('All', 'Alle'),
('Apply all', 'Speichern'),
('date/time error', 'Datum/Uhrzeit'),
('Back', 'Zurück'),
('by', 'von');

INSERT INTO `captions` (`capt`, `repl`) VALUES
('RESERVED TICKET', 'Noch nicht vergeben'),
('Download zip-file', 'Datei runterladen'),
('Downloading update', 'Aktualisierung wird heruntergeladen'),
('Downloading update finished', 'Aktualisierung herunterladen abgeschlossen'),
('Downloading update failed', 'Aktualisierung herunterladen fehlgeschlagen'),
('Click to message', 'Nachricht an'),
('Software-Version', 'Software-Version'),
('Localization', 'Lokalisierung'),
('Server OS', 'Server-Betriebssystem'),
('PHP-Version', 'PHP-Version'),
('Database', 'Datenbank'),
('Database-Table', 'Datenbank-Tabelle'),
('Server time', 'Server-Zeit'),
('Delta mins', 'Max. Delta (Min.)'),
('Reserved', 'Reserviert'),
('Units in database', 'Einheiten in Datenbank'),
('Users in database', 'Benutzer in Datenbank'),
('Log records in database', 'Protokolleinträge in Datenbank'),
('Current User', 'Aktueller Benutzer'),
('Current version', 'Aktuelle Version'),
('Visting from', 'Client-IP und -Hostname'),
('Browser', 'Webbrowser'),
('bg_color', 'Hintergundfarbe'),
('Comment', 'Manuelle Eingabe'),
('Call edit', 'Einheit - Disposition bearbeitet'),
('Call Facility set', 'Einheit - Abweichender Transportstart ausgewählt'),
('Call Facility changed', 'Einheit - Abweichender Transportstart geändert'),
('Call Facility unset', 'Einheit - Abweichender Transportstart zurückgesetzt'),
('Call rcv Facility set', 'Einheit - Transportziel ausgewählt'),
('Call rcv Facility changed', 'Einheit - Transportziel geändert'),
('Call rcv Facility unset', 'Einheit - Transportziel zurückgesetzt'),
('Call closed', 'Folgender Einsatz wurde geschlossen'),
('Call type', 'Art'),
('Caller', 'Anrufer'),
('Call destination', 'Ziel'),
('Check all', 'Alle auswählen'),
('check days value', 'Angabe des Zeitraums überprüfen!'),
('City and State are required for location lookup.', 'Kein Hinweistext verfügbar.'),
('Show release notes', 'Versionshinweise anzeigen'),
('Click to sort by Incident', 'Hier klicken um nach Einsatzorten zu sortieren.'),
('Click to sort by Unit', 'Hier klicken um nach Einheiten zu sortieren.'),
('Close', 'Schliessen'),
('Closed', 'Geschlossen');

INSERT INTO `captions` (`capt`, `repl`) VALUES
('Closed ticket requires disposition data', 'Schlussmeldung im Feld Bemerkungen'),
('Closed tickets', 'Geschlossene Einsätze'),
('Closed tickets_short', 'Geschlossene'),
('Code', 'Meldung'),
('Color', 'Farbe'),
('Confirm do not send?', 'Nachricht nicht versenden?'),
('Contact', 'Kontakt'),
('Email', 'E-Mail'),
('Comments', 'Bemerkungen'),
('Cleared', 'Disposition geschlossen!'),
('Client address', 'IP-Adresse'),
('Comments required', 'Bemerkungen'),
('Confirm', 'Passwort bestätigen'),
('Confirm CAPTCHA', 'Zufallstext eingeben'),
('Copy dataset', 'Kopieren'),
('Last login', 'Letzte Anmeldung'),
('Captions and Hints', 'Übersetzungen und Hinweistexte'),
('Captions', 'Übersetzungen'),
('Could not set units status values to', 'Status setzen nicht möglich'),
('Could not set facility status values to', 'Status setzen nicht möglich'),
('Click right to set callprogression', 'Rechte Maustaste: Status eingeben'),
('Click to edit assign', 'Linke Maustaste: Disposition bearbeiten'),
('Click to edit log report', 'Linke Maustaste: Einsatztagebuch-Eintrag'),
('Click right to set status', 'Rechte Maustaste: Status eingeben'),
('Multidispatch - click to select assign', 'Linke Maustaste: Mehrfachdisposition - Einsatz auswählen'),
('Multidispatch - Select ticket', 'Mehrfachdisposition - Einsatz auswählen'),
('call  reset', 'call  reset'),
('Configuration Edit', 'Einstellungen bearbeitet'),
('Day', 'Tag'),
('days', 'Tage'),
('DateTime', 'Uhrzeit'),
('Date', 'Datum');

INSERT INTO `captions` (`capt`, `repl`) VALUES
('Delete', 'Löschen'),
('Description is required', 'Beschreibung'),
('Action description', 'Rückmeldung'),
('Dispatched Units', 'Eingesetzte Einheiten'),
('Display dispatch-message for printing', 'Alarmschreiben zum Drucken anzeigen'),
('Disposition is required', 'Bemerkungen'),
('Dock', 'ankoppeln'),
('Saved', 'Gespeichert'),
('Deleted', 'Gelöscht'),
('An update is only possible to the next version.', 'Eine Aktualisierung ist immer nur auf die nächst höhere Version möglich.'),
('Assign deleted', 'Disposition gelöscht'),
('Assign calls deleted', 'Disposition zurückgesetzt'),
('Delete this dispatch record?', 'Disposition löschen?'),
('Database functions and updates', 'Datenbank und Aktualisierungen'),
('Day / Night', 'Tag / Nacht'),
('delete(yes)', 'Löschen(Ja)'),
('DENIED! - User has active database records', 'Löschen nicht möglich - Datenbankeinträge vorhanden'),
('Data Import', 'Ergebnis des Datenimports'),
('Dataset unit_types added', 'Datensatz Einheiten-Konfiguration gespeichert'),
('Dataset unit_types deleted', 'Datensatz Einheiten-Konfiguration gelöscht'),
('Dataset un_status added', 'Datensatz Einheiten-Status gespeichert'),
('Dataset un_status deleted', 'Datensatz Einheiten-Status gelöscht'),
('Dataset unit added', 'Datensatz Einheiten gespeichert');

INSERT INTO `captions` (`capt`, `repl`) VALUES
('Dataset unit deleted', 'Datensatz Einheiten gelöscht'),
('Dataset textblocks synopsis added', 'Datensatz Textbaustein-Notfallsituation gespeichert'),
('Dataset textblocks synopsis deleted', 'Datensatz Textbaustein-Notfallsituation gelöscht'),
('Dataset textblocks description added', 'Datensatz Textbaustein-Bemerkung gespeichert'),
('Dataset textblocks description deleted', 'Datensatz Textbaustein-Bemerkung gelöscht'),
('Dataset textblocks action added', 'Datensatz Textbaustein-Rückmeldung gespeichert'),
('Dataset textblocks action deleted', 'Datensatz Textbaustein-Rückmeldung gelöscht'),
('Dataset textblocks assign added', 'Datensatz Textbaustein-Disposition gespeichert'),
('Dataset textblocks assign deleted', 'Datensatz Textbaustein-Disposition gelöscht'),
('Dataset textblocks close added', 'Datensatz Textbaustein-Schlussmeldung gespeichert'),
('Dataset textblocks close deleted', 'Datensatz Textbaustein-Schlussmeldung gelöscht'),
('Dataset textblocks log added', 'Datensatz Textbaustein-Einsatztagebuch gespeichert'),
('Dataset textblocks log deleted', 'Datensatz Textbaustein-Einsatztagebuch gelöscht'),
('Dataset textblocks message added', 'Datensatz Textblock-Nachrichten gespeichert'),
('Dataset textblocks message deleted', 'Datensatz Textblock-Nachrichten gelöscht'),
('Dataset textblocks fixtext added', 'Datensatz Fixmeldungen gespeichert'),
('Dataset textblocks fixtext deleted', 'Datensatz Fixmeldungen gelöscht'),
('Dataset in_types added', 'Datensatz Einsatzstichwort gespeichert'),
('Dataset in_types deleted', 'Datensatz Einsatzstichwort gelöscht'),
('Dataset captions updated', 'Datensatz Übersetzung aktualisiert'),
('Dataset hints updated', 'Datensatz Hinweistext aktualisiert'),
('Dataset fac_types added', 'Datensatz Objekt-Kategorie gespeichert'),
('Dataset fac_types deleted', 'Datensatz Objekt-Kategorie gelöscht'),
('Dataset fac_status added', 'Datensatz Objekt-Status gespeichert'),
('Dataset fac_status deleted', 'Datensatz Objekt-Status gelöscht'),
('Dataset facility added', 'Datensatz Objekt gespeichert'),
('Dataset facility deleted', 'Datensatz Objekt gelöscht'),
('Dataset settings updated', 'Datensatz Einstellung aktualisiert'),
('Dataset user added', 'Datensatz Benutzer gespeichert'),
('Dataset user updated', 'Datensatz Benutzer aktualisiert'),
('Dataset user deleted', 'Datensatz Benutzer gelöscht'),
('Database optimization complete.', 'Optimierung der Datenbank durchgeführt.'),
('Display', 'Anzeigen'),
('Dispatch text', 'Alarmschreiben'),
('Email sent', 'E-Mail verschickt'),
('Email not sent', 'E-Mail - Fehler'),
('Edit', 'Bearbeiten'),
('Edit Action', 'Rückmeldung bearbeiten'),
('Edit this Call Assignment', 'Disposition bearbeiten'),
('Edit Ticket', 'Einsatz bearbeiten'),
('Edit unit', 'Einheit'),
('Edit unit data', 'Einheit bearbeiten'),
('Edit Facility data', 'Objekt bearbeiten'),
('Edit User Data', 'Benutzerkonto bearbeiten'),
('Elapsed', 'Einsatzdauer');

INSERT INTO `captions` (`capt`, `repl`) VALUES
('End Miles', 'KM Ende'),
('End mileage error', 'KM Ende-Fehler'),
('Enter r to Reset dispatch times.', 'Einsatzzeiten zurücksetzen: r'),
('Enter d to Delete this dispatch.', 'Disposition löschen: d'),
('Error', 'Fehler'),
('Export', 'Exportieren'),
('Facilities legend', 'Kategorien'),
('Facilities', 'Objekte'),
('Use incident location', 'Einsatzort übernehmen'),
('Free input', 'Freie Eingabe');

INSERT INTO `captions` (`capt`, `repl`) VALUES
('Facility', 'Objekt'),
('Facility name', 'Name'),
('Facility handle', 'Kurzbezeichnung'),
('Facility Status', 'Status'),
('Facility contact', 'Anschrift'),
('Facility type', 'Kategorie'),
('Facility HANDLE is required.', 'Kurzbezeichnung'),
('Facility Name', 'Objektname'),
('Facility NAME is required.', 'Name'),
('Facility State', 'Staat des Objekts'),
('Facility STATUS is required.', 'Status'),
('Facility status changed', 'Objekt - Status geändert'),
('Facility Street', 'Straße des Objekts'),
('Facility type selection is required.', 'Kategorie'),
('Facility added', 'Objekt - Stammdaten neu angelegt'),
('Facility changed', 'Objekt - Stammdaten geändert'),
('Facility Incident opened', 'Einsatzort aus Objektliste ausgewählt'),
('Facility Incident unset', 'Einsatzort aus Objektliste zurückgesetzt'),
('Facility Incident changed', 'Einsatzort aus Objektliste geändert'),
('Facility dispatched', 'Einsatzort aus Objektliste zugeordnet'),
('Facility status values set to', 'Ausgewählte Objekte gesetzt auf'),
('Facility deleted', 'Objekt - Stammdaten gelöscht'),
('Facility has been deleted from database', 'Objekt aus Datenbank gelöscht.'),
('Facility inserted', 'Objekt gespeichert'),
('Fac en-route', 'Ab(7)'),
('Fac en-route without ticket', 'Ab(7) ohne Einsatz'),
('Fac arr', 'An(8)'),
('Fac arr without ticket', 'An(8) ohne Einsatz'),
('Facilities Configuration', 'Objekte'),
('Get links', 'Verbindungen');

INSERT INTO `captions` (`capt`, `repl`) VALUES
('Region assigned', 'Bereich(e)'),
('General', 'Allgemeines'),
('Helptext', 'Hilfe'),
('Hide', 'Ausblenden'),
('Hide closed assigns', 'Nur Aktive'),
('hr', 'Stunde'),
('hrs', 'Stunden'),
('Hints', 'Hinweistexte'),
('Tag', 'Element'),
('Incident closed', 'Einsatz geschlossen');

INSERT INTO `captions` (`capt`, `repl`) VALUES
('Incident added', 'Einsatz angelegt'),
('Incident opened', 'Einsatz eröffnet'),
('Incident scheduled', 'Einsatz vorbestellt'),
('Incident updated', 'Einsatz bearbeitet'),
('Invalid Ticket ID', 'Ungültige Einsatznummer'),
('Incident name is required', 'Einsatznummer'),
('Ticket Log', 'Protokoll Einsatzleitrechner'),
('Incident Numbers', 'Einsatznummern'),
('Incident number settings updateted', 'Einsatznummer - Einstellungen gespeichert'),
('Incident Add/Edit hints - enter revisions', 'Hinweistexte bearbeiten'),
('Incident Add/Edit captions - enter revisions', 'Übersetzungen bearbeiten'),
('Lat', 'Koordinaten - Breite'),
('Lng', 'Koordinaten - Länge'),
('Level', 'Benutzerrolle'),
('Facility address', 'Strasse, Hausnummer');

INSERT INTO `captions` (`capt`, `repl`) VALUES
('For an update, write permission is missing for', 'Für eine Aktualisierung fehlen schreibberechtigung für'),
('Log-error', 'Systemfehler'),
('Log-info', 'Systemmeldung'),
('Login failed. Please enter correct values and try again.', 'Anmeldung fehlgeschlagen. Bitte versuchen Sie es erneut.'),
('List and Cleanse Region Allocations', 'Bereinigen'),
('Map', 'Karte'),
('Make changes', 'Änderungen vornehmen'),
('Make changes finished', 'Änderungen vornehmen abgeschlossen'),
('Make changes failed', 'Änderungen vornehmen fehlgeschlagen'),
('Message', 'Textnachricht'),
('Message and Private Call', 'Textnachricht und Einzelruf'),
('Message already edited', 'Meldung bereits bearbeitet'),
('Message fixtext', 'Fixmeldung'),
('Message fixtexts', 'Fixmeldungen'),
('Message not sent', 'Nachricht nicht gesendet'),
('Message Receieve', 'Nachricht empfangen'),
('Message shorttext', 'Kurztext'),
('Message sent', 'Nachricht gesendet'),
('Message text required', 'Nachrichtentext eingeben'),
('Message text', 'Nachricht'),
('Message texts', 'Nachrichten'),
('Remote data services', 'Datendienste'),
('Mileage', 'Kilometerstand'),
('min', 'Minute'),
('mins', 'Minuten'),
('ml', 'Meilen'),
('mos', 'Monate'),
('Select the period', 'Berichtszeitraum'),
('Dispatchable', 'Disponierbar'),
('Multiple dispatchable', 'Mehrfach disponierbar'),
('Communication', 'Kommunikation');

INSERT INTO `captions` (`capt`, `repl`) VALUES
('Mobility', 'Bewegungsprofil'),
('mo', 'Monat'),
('inc_name_short', 'E-Nr.'),
('Messaging Settings', 'Einstellungen'),
('Message Archiving', 'Archiv'),
('Max. Filesize(kb)', 'Max. Dateigröße in Kilobyte'),
('NA', 'k.A.'),
('NA - calls in progress', 'Nicht möglich, da Einheit im Einsatz ist.'),
('NA - superadmin only', 'Nicht möglich, Änderungen nur durch Administrator erlaubt.'),
('Incident type is required', 'Einsatzstichwort'),
('New Action record by', 'Rückmeldung angelegt durch'),
('New Password', 'Neues Passwort'),
('New ticket', 'Neuen Einsatz eröffnen'),
('Yes', 'Ja'),
('Append nature', 'Einsatzstichwort anhängen'),
('Incident name manual edit', 'Einsatznummer manuell vergeben'),
('Incident name with counter', 'Einsatznummer mit Zähler'),
('Incident name with Database-ID', 'Einsatznummer mit Datenbank-ID'),
('Use Table-ID', 'Tabellen-ID verwenden'),
('Label12345', 'Präfix[Trennzeichen]12345'),
('YR12345', 'Jahr[Trennzeichen]12345'),
('Incident name Label', 'Präfix'),
('Incident name Separator', 'Trennzeichen'),
('Next number', 'Nächste Einsatznummer'),
('Label not used with this option', 'Präfix wird bei dieser Einstellung nicht berücksichtigt'),
('Next number must be numeric', 'Nächste Einsatznummer muss numerisch sein'),
('Next number must be 1 or greater', 'Nächste Einsatznummer muss 1 oder höher sein'),
('Label required  with this option', 'Präfix wird bei dieser Einstellung benötigt'),
('Free_text/NO#12345', 'Freitext/#12345'),
('Free_text(add)', 'Freitext (nur beim Anlegen)'),
('Free_text(edit)', 'Freitext (Bearbeiten möglich)'),
('No', 'Nein'),
('NO#12345', '#12345'),
('NO#12345/Free_text', '#12345/Freitext'),
('NO12345', '12345'),
('No, enforceable', 'Bedingt'),
('No evaluation', 'Keine Auswertung'),
('No printers found!', 'Keine Drucker gefunden! Diese Funktion ist nur verfügbar auf Systemen mit Common Unix Printing System® (CUPS), z.B. Mac® OS oder Linux®. Auf Microsoft Windows® basierenden Systemen muss der Druckerpfad manuell ermittelt werden.'),
('No addresses available!', 'Keine Verbindungsdaten hinterlegt!'),
('No addresses.', 'Keine Empfänger verfügbar'),
('No answer from foreign host.', 'Keine Antwort vom Ziel-Host.'),
('No data', 'Keine Daten'),
('No data for this period!', 'Für den gewählten Zeitraum sind keine Daten verfügbar!'),
('No data for this filter!', 'Für den gewählten Filter sind keine Daten verfügbar!'),
('No facilities created!', 'Keine Objekte angelegt!'),
('No facilities available!', 'Keine Objekte verfügbar!'),
('No filter set.', 'Kein Filter gesetzt.'),
('No info-text available.', 'Kein Info-Text übermittelt.'),
('No textblocks available!', 'Keine Textbausteine verfügbar!'),
('No receiver available', 'Keine Empfänger angegeben'),
('No units created!', 'Keine Einheiten angelegt!'),
('No units in service!', 'Keine Einheiten im Dienst!'),
('No units available!', 'Keine Einheiten verfügbar!'),
('No updates pending.', 'Die Software ist auf der neuesten Version.'),
('No message to edit', 'Keine Meldung zu bearbeiten'),
('No, enforced ', 'Alarmierbar an Wache'),
('No, not enforced', 'Nicht Alarmierbar');

INSERT INTO `captions` (`capt`, `repl`) VALUES
('None selected', 'Keine'),
('Not available since', 'Nicht verbunden seit'),
('Not all saved', 'Nicht alle gespeichert'),
('Not available', 'nicht verfügbar'),
('Not configured.', 'Nicht konfiguriert.'),
('Not dispatchable', 'Nicht disponierbar'),
('Not reach all recipients', 'Nicht alle Empfänger erreicht'),
('Not saved', 'Nicht gespeichert'),
('No units dispatched!', 'Keine Einheiten eingesetzt!'),
('None', 'keine'),
('No closed tickets this period!', 'Keine Einsätze im gewählten Zeitraum!'),
('No current tickets!', 'Keine offenen Einsätze!'),
('No action', 'Keine Bearbeitung'),
('No actions.', 'Keine Rückmeldungen.'),
('No assigned Responder.', 'Keine disponierten Einheiten.'),
('No connection to the update server.', 'Keine Verbindung zum Aktualisierungs-Server.'),
('No current dispatches', 'Keine Einheiten im Einsatz!'),
('No group name', 'Keine Gruppenname'),
('No help Text available.', 'Kein Hinweistext verfügbar.'),
('No release-notes found.', 'Keine Versionshinweise gefunden.'),
('No User addresses available!', 'Keine E-Mail-Adressen verfügbar!'),
('Native PHP Mail', 'PHP E-Mail'),
('Nothing to do - Caution: Use CSV-Fileformat with Semicolon as Field delimiter!', 'Keine verarbeitungsfähigen Daten gefunden - Beachten: Semikolon als Feldtrenner verwenden'),
('Nothing to do!', 'Kein auszuführender Auftrag vorhanden!'),
('Object id', 'Objektnummer'),
('of', 'von'),
('OK', 'OK'),
('one month', 'einen Monat'),
('Online', 'Angemeldet'),
('On Scene Miles', 'KM Einsatzstelle'),
('On Ticket Change', 'Bei Änderung der Einsatzdaten'),
('On Action', 'Rückmeldung'),
('Once dispatchable', 'Einfach disponierbar'),
('one day', 'ein Tag'),
('one week', 'eine Woche'),
('Open', 'Offen');

INSERT INTO `captions` (`capt`, `repl`) VALUES
('OSGB', 'OSGB'),
('On scene mileage error', 'KM Einsatzstelle-Fehler'),
('Passwd length 6 or more is required.', 'Passwort mit mindestens 6 Zeichen'),
('Passwd and confirmation must match.', 'Passwörter müssen übereinstimmen'),
('PASSWORD is required.', 'Passwort'),
('Page', 'Seite'),
('Please confirm removing', 'Löschen bestätigen'),
('Please correct the following and re-submit', 'Bitte Eingaben korrigieren'),
('Please login', 'Bitte melden Sie sich an'),
('Please select units, or cancel', 'Bitte Einheiten auswählen oder abbrechen!'),
('Position message', 'Positionsmeldung');

INSERT INTO `captions` (`capt`, `repl`) VALUES
('Presentation', 'Darstellung'),
('Print job completed', 'Duckauftrag verschickt'),
('Print job failed', 'Druckauftrag - Fehler'),
('Receipt', 'Statuszuweisung'),
('Receiver', 'Empfänger'),
('Receiving location', 'Transportziel'),
('Refresh', 'Aktualisieren'),
('Regions', 'Bereiche'),
('Reply', 'Antworten'),
('Reporting channel', 'Meldeweg'),
('Report type', 'Suchen in'),
('Reset dispatch', 'Disposition zurücksetzen'),
('Reset unit dispatch times or Delete dispatch', 'Zeiten oder gesamte Disposition zurücksetzen'),
('Resourced', 'Einheit disponiert'),
('Handle request', 'Bearbeiten'),
('Send message', 'Nachricht versenden'),
('Reset', 'Zurücksetzen'),
('Reported-by is required', 'Meldender'),
('Invalid scheduled date', 'Vorbestellt'),
('invalid smtp-host', 'ungültiger smtp-Server'),
('Invalid problemstart', 'Einsatzbeginn'),
('Invalid problemend', 'Einsatzende'),
('Invalid dispatched datetime', 'Datum/Zeit - Alarmiert'),
('Invalid responding datetime', 'Datum/Zeit - Aus(3)'),
('Invalid on-scene datetime', 'Datum/Zeit - Ein(4)'),
('Invalid facility-enroute datetime', 'Datum/Zeit - Ab(7)'),
('Invalid facility-arrived datetime', 'Datum/Zeit - An(8)'),
('Invalid clear datetime', 'Datum/Zeit - Frei(1)'),
('Set units to a common status', 'Einheiten auf gleichen Status setzen'),
('Set facilities to a common status', 'Objekte auf gleichen Status setzen');

INSERT INTO `captions` (`capt`, `repl`) VALUES
('Units status values set to', 'Ausgewählte Einheiten gesetzt auf'),
('Reset Regions', 'Bereiche zurücksetzen'),
('Reset all resources back to first Region?', 'Alle Bereiche auf den ersten Bereich zurücksetzen?'),
('Direct dialing 2', 'Durchwahl-Nummer 2'),
('Second', 'Sekunde'),
('Send', 'Versenden'),
('Severity', 'Priorität'),
('Show All', 'Alles anzeigen'),
('Show Menu', 'Menü zeigen'),
('Show closed assigns', 'Alle Anzeigen'),
('Showing Regions', 'angezeigte Bereiche'),
('Sign in', 'Angemeldet'),
('Sign out', 'Abgemeldet'),
('Standard Message', 'Standardmeldungen'),
('Start update', 'Aktualisierung starten'),
('Start Miles', 'KM Anfang'),
('Log report', 'Einsatztagebuch');

INSERT INTO `captions` (`capt`, `repl`) VALUES
('Select', 'Auswahl'),
('Select all', 'Alle'),
('Select printer', 'Drucker auswählen'),
('Select Unit', 'Einheit'),
('Select Units', 'Einheit auswählen'),
('selected', 'ausgewählt'),
('Selected for transfer in the Callback number field on the New-ticket and Edit-ticket page.', 'Für die Übernahme in das Feld Rückruf-Nummer auf den Seiten Neuer-Einsatz und Einsatz-bearbeiten ausgewählt.'),
('Subject', 'Betreff'),
('Save', 'Speichern'),
('Save and copy dataset', 'Speichern und Kopieren'),
('Key', 'Variable'),
('Value', 'Wert'),
('Scheduled', 'Vorbestellt'),
('Scheduled tickets', 'Vorbestellte Einsätze'),
('Scheduled tickets_short', 'Vorbestellungen'),
('Synopsis is required', 'Notfallsituation'),
('SMS sent', 'Kurznachricht verschickt'),
('SMS not sent', 'Kurznachricht - Fehler'),
('Start mileage error', 'KM Anfang-Fehler'),
('Textblock', 'Textbaustein'),
('Textblocks', 'Textbausteine'),
('Textblocks inserted', 'Textbausteine gespeichert'),
('Textblocks synopsis', 'Notfallsituation'),
('Textblocks description', 'Bemerkungen'),
('Textblocks action', 'Rückmeldung'),
('Textblocks assign', 'Disposition'),
('Textblocks incident close', 'Schlussmeldung'),
('Textblocks log', 'Einsatztagebuch'),
('Textblocks message', 'Nachrichten'),
('Tickets in database', 'Einsätze in Datenbank'),
('Time taken on in disposition', 'In Disposition übernommene Zeit'),
('Set units status to a common setting', 'Auf gleichen Status setzen'),
('System Summary', 'Systeminformationen'),
('Set facilities status to a common setting', 'Auf gleichen Status setzen'),
('SMTP Mail', 'SMTP E-Mail');

INSERT INTO `captions` (`capt`, `repl`) VALUES
('play it', 'Abspielen'),
('alternative format sound file(optional)', 'Sound-Datei (anderes Format, optional)'),
('sound file', 'Sound-Datei'),
('audio_default', 'Sonstiges Ereignis'),
('audio_ticket', 'Einsatz - Neu'),
('audio_status', 'Einheiten Status - Änderung'),
('audio_dispatch', 'Disposition - Neu'),
('audio_action', 'Rückmeldung - Neu/Änderung'),
('audio_call_request', 'Sprechwunsch(5)'),
('audio_new_message', 'Neue Nachricht'),
('audio_emergency_low', 'Hilferuf(0)'),
('audio_emergency_high', 'Notruf'),
('audio_call_progression', 'Einheiten Status - Einsatzfortschritt'),
('Audio files updated', 'Hinweistöne gespeichert'),
('Settings saved (will take effect at next re-start)', 'Einstellungen gespeichert (Neuanmeldung erforderlich)'),
('Seconds', 'Sekunden'),
('Test', 'Test'),
('time zone', 'Zeitzone'),
('Text', 'Text'),
('Call Board Module', 'Einsatzzeiten'),
('to', 'bis'),
('To top', 'Nach Oben'),
('TOTAL MILES', 'KM Gesamt');

INSERT INTO `captions` (`capt`, `repl`) VALUES
('Requires a iframes-capable browser.', 'Die Anwendung benötigt einen Browser, der Frames darstellen kann.'),
('Total mileage error', 'KM Gesamt-Fehler'),
('total', 'Gesamt'),
('permission_super', 'Administrator'),
('permission_admin', 'Schichtführer'),
('permission_operator', 'Disponent'),
('permission_guest', 'Info'),
('Table', 'Tabelle'),
('Table-ID', 'Tabellen-ID'),
('Unit status configuration', 'Einheiten-Status bearbeiten'),
('Unit types configuration', 'Einheiten-Kategorien bearbeiten'),
('Facility status configuration', 'Objekt-Status bearbeiten'),
('Facility types configuration', 'Objekt-Kategorien bearbeiten'),
('Incident Types Configuration', 'Einsatzstichworte bearbeiten'),
('New entry', 'Neuer Eintrag'),
('Query text', 'Suchtext'),
('Undock', 'abkoppeln'),
('unknown', 'unbekannt'),
('Units assigned to Incident', 'Nur an Einheiten im Einsatz'),
('Unit added', 'Einheit - Stammdaten neu angelegt'),
('Unit changed', 'Einheit - Stammdaten geändert'),
('Units legend', 'Kategorien'),
('Unit Log', 'Einheiten'),
('Units responding', 'Ausgerückte Einheiten'),
('Update call progression', 'In Disposition übernehmen'),
('Status update applied', 'Status aktualisiert'),
('Assign update applied', 'Disposition gespeichert'),
('Unit NAME is required.', 'Funkrufname'),
('Unit HANDLE is required.', 'Funk-Code');

INSERT INTO `captions` (`capt`, `repl`) VALUES
('Unit type selection is required.', 'Kategorie'),
('Units STATUS is required.', 'Status'),
('Unit status change', 'Einheit - Status geändert'),
('Unit out of Service', 'Ausser Dienst(6)'),
('Unit to Quarters', 'Wache(2)'),
('Call Request', 'Sprechwunsch(5)'),
('manual acknowledgment', 'Handquittung(9)'),
('Emergency Call low', 'Hilferuf(0)'),
('Emergency Call high', 'Notruf'),
('Push to Talk', 'Sprechtaste'),
('Push to Talk release', 'Sprechtaste losgelassen'),
('Update', 'Aktualisieren'),
('Update started to version', 'Aktualisierung gestartet. Nächste Version'),
('Update-Server', 'Aktualisierungs-Server'),
('Update progress', 'Aktualisierungsfortschritt'),
('SVN project files still exist. Update is only simulated.', 'SVN-Projektdateien sind noch vorhanden. Aktualisierung wird nur simuliert.'),
('Updates', 'Aktualisierungen'),
('Unpacking files', 'Dateien auspacken'),
('Unpacking files finished', 'Dateien auspacken abgeschlossen'),
('Unpacking files failed', 'Dateien auspacken fehlgeschlagen'),
('User ID', 'Benutzername'),
('User has been added', 'Neuen Benutzer angelegt'),
('User data has been updated', 'Daten aktualisiert von Benutzer'),
('User LEVEL is required.', 'Benutzerrolle'),
('UTM', 'UTM'),
('Units selection is required.', 'Einheit auswählen'),
('UserID is required.', 'Benutzernamen'),
('UserID duplicates existing one.', 'Anderen Benutzernamen auswählen'),
('Units Configuration', 'Einheiten'),
('Unit type', 'Kategorie'),
('Saved and copied', 'Gespeichert und kopiert'),
('Unit status', 'Status'),
('Users', 'Benutzerkonten'),
('Upload', 'Hochladen'),
('User has been deleted', 'Benutzer gelöscht.'),
('Unsaved duplicates', 'Unbearbeitete Doubletten'),
('Unit deleted', 'Einheit - Stammdaten gelöscht'),
('Voice promt', 'Sprechaufforderung'),
('Voice promt sent', 'Sprechaufforderung gesendet');

INSERT INTO `captions` (`capt`, `repl`) VALUES
('View current situation', 'Lageübersicht'),
('Viewed Regions', 'sichtbare Bereiche'),
('Wait', 'Warten'),
('With', 'mit'),
('yr', 'Jahr'),
('yrs', 'Jahre'),
('You cannot change this value', 'Daten können nicht geändert werden!'),
('Your profile has been updated.', 'Eigene Daten gespeichert'),
('You cannot Hide all the regions', 'Mindestens einen Bereich auswählen!'),
('Start configuration wizard', 'Zum Konfigurationsassistenten');

INSERT INTO `captions` (`capt`, `repl`) VALUES
('Preview defaults', 'Vorschau anzeigen'),
('Units and / or facilitys have already been created in this installation. The configuration wizard can only be executed after a new installation!', 'Es sind bereits Einheiten und / oder Objekte in dieser Installation angelegt. Der Konfigurationsassistenten kann nur nach einer Neuinstallation ausgeführt werden!'),
('Basic Configuration', 'Grundkonfiguration erstellen'),
('Add Line', 'Neue Zeile'),
('Next Page', 'Weiter'),
('Next version', 'Nächste Version'),
('Close Help', 'Hilfe schliessen'),

('1 of 6 - Introduction', '1 von 6 - Einführung'),
('2 of 6 - Titles', '2 von 6 - Kopf- und Seitenbeschriftung'),
('Head Caption', 'Beschriftung in der Kopfleiste'),
('Page Caption', 'Beschriftung im Seitentitel'),

('3 of 6 - Incident-types and textblocks', '3 von 6 - Einsatzstichworte und Textbausteine'),
('Sort group', 'Gruppierung'),

('4 of 6 - Units', '4 von 6 - Einheiten'),
('_example_unit_handle_1', 'Re MUS RTW 1'),
('_example_unit_name_1', 'Rettung Musterstadt RTW 1'),
('_example_unit_handle_2', 'Re MUS KTW 1'),
('_example_unit_name_2', 'Rettung Musterstadt KTW 1'),

('5 of 6 - Unit types', '5 von 6 - Einheiten-Kategorien'),
('_example_unit_type_name_1', 'Rettungsdienst'),
('_example_unit_type_descr_1', 'Rettungsdienst'),
('_example_unit_type_bgcolor_1', 'F0F0F0'),
('_example_unit_type_txtcolor_1', '000000'),
('_example_unit_type_name_2', 'Katastrophenschutz'),
('_example_unit_type_descr_2', 'Katastrophenschutz'),
('_example_unit_type_bgcolor_2', 'FFFF00'),
('_example_unit_type_txtcolor_2', '000000'),
('_example_unit_type_name_3', 'Erstversorgungsteam'),
('_example_unit_type_descr_3', 'Erstversorgungsteam'),
('_example_unit_type_bgcolor_3', '66CCFF'),
('_example_unit_type_txtcolor_3', '000000'),
('_example_unit_type_name_4', 'Sonstiges'),
('_example_unit_type_descr_4', 'Sonstiges'),
('_example_unit_type_bgcolor_4', 'C0C0C0'),
('_example_unit_type_txtcolor_4', '000000'),

('Background Color', 'Hintergrundfarbe'),
('Text Color', 'Textfarbe'),
('Able to dispatch', 'Disposition möglich'),
('Can dispatch', 'Ja'),
('Not enforceable', 'Nein'),

('6 of 6 - Facilities', '6 von 6 Objekte'),
('_example_facility_type_name', 'Sonst. Objekt'),
('_example_facility_type_description', 'Wohn- / Geschäftsgebäude, Wache / Gerätehaus, usw.'),
('_example_facility_handle_1', 'Hauptbühne'),
('_example_facility_name_1', 'Hauptbühne auf dem Festplatz'),
('_example_facility_street_1', 'Festplatz 1 - 10'),
('_example_facility_city_1', '12345 Musterstadt'),
('_example_facility_handle_2', 'K1, städt. Krankenhaus'),
('_example_facility_name_2', 'Städtische Krankenanstalten gGmbH'),
('_example_facility_street_2', 'Hauptstraße 1'),
('_example_facility_city_2', '12345 Musterstadt'),
('Finish', 'Konfiguration speichern'),

('Setup Complete', 'Konfiguration abgeschlossen'),
('Title String Set', 'Beschriftung Kopfleiste gespeichert'),
('Page Caption Set', 'Beschriftung Seitentitel gespeichert'),
('Default Server Time Difference Set', 'Max. Zeitdifferenz(Min.) Server/Client gespeichert'),
('Unit type inserted', 'Einheiten-Kategorie gespeichert'),
('Responder Status inserted', 'Einheiten-Status gespeichert'),
('Unit inserted', 'Einheit gespeichert'),
('Go to login', 'Zur Anmeldeseite');

INSERT INTO `captions` (`capt`, `repl`) VALUES
('Database Configuration', 'Datenbank-Einstellungen'),
('Username', 'Benutzername'),
('DB-Host', 'Hostname'),
('Default textblocks', 'Muster-Textbausteine'),
('Default incident types', 'Muster-Einsatzstichworte'),
('Install Option', 'Optionen'),
('Install database tables new (drop tables if exist)', 'Neuinstallation, alle vorhandenen Daten werden gelöscht.'),
('Install default incident types', 'Muster-Einsatzstichworte installieren'),
('Install default textblocks', 'Muster-Textbausteine installieren'),
('random text', 'Zufallstext'),
('Reset settings (do not touch user data)', 'Einstellungen zurücksetzen, vorhandene Daten bleiben erhalten.'),
('Write db-configuration file only', 'Zugangsdaten der Datenbank neu speichern, alle Daten bleiben erhalten.');

INSERT INTO `captions` (`capt`, `repl`) VALUES
('Facilities presentation configuration', 'Objekt-Darstellung bearbeiten'),
('Units presentation configuration', 'Einheiten-Darstellung bearbeiten'),
('Tab order preview', 'Vorschau der Reiter-Reihenfolge'),
('Admin can add', 'Schichtführer kann zufügen'),
('Tab name', 'Reiter-Name'),
('Visible', 'Sichtbar'),
('Add tickets', 'Einsätze zeigen'),
('Columns', 'Spalten'),
('Rows', 'Zeilen'),
('Admin can config', 'Schichtführer kann bearbeiten'),
('Facility tab', 'Objekt-Reiter'),
('Unit tab', 'Einheiten-Reiter'),
('Singlemonitor only', 'Ein Bildschirm'),
('Multimonitor only', 'Mehrere Bildschirme'),
('Tab show/hide', 'Reiter ein-/ausblenden'),
('Tab edit/delete', 'Reiter editieren/löschen'),
('Set to admin can add facility tabs', 'Schichtführer kann Objekt-Reiters zufügen gespeichert'),
('Set to admin can not add facility tabs', 'Schichtführer kann Objekt-Reiters nicht zufügen gespeichert'),
('New facility tab added', 'Neuer Objekt-Reiter zugefügt'),
('Facilty tabs updated', 'Objekt-Reiter geändert'),
('Facility tabs deleted', 'Objekt-Reiter gelöscht'),
('Set to admin can add unit tabs', 'Schichtführer kann Einheiten-Reiters zufügen gespeichert'),
('Set to admin can not add unit tabs', 'Schichtführer kann Einheiten-Reiters nicht zufügen gespeichert'),
('New unit tab added', 'Neuer Einheiten-Reiter zugefügt'),
('Unit tabs updated', 'Einheiten-Reiter geändert'),
('Unit tabs deleted', 'Einheiten-Reiter gelöscht'),
('Changed Tab name', 'Geänderter Reiter-Name'),
('Deleted Tab name', 'Gelöschter Reiter-Name'),
('Edit custom units representation', 'Benutzerdefinierte Einheiten-Darstellung bearbeiten'),
('Edit custom facilities representation', 'Benutzerdefinierte Objekt-Darstellung bearbeiten'),
('Row', 'Zeile'),
('Column', 'Spalte');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
