SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

DROP TABLE IF EXISTS `actions`;

DROP TABLE IF EXISTS `allocates`;

DROP TABLE IF EXISTS `api_log`;

DROP TABLE IF EXISTS `assigns`;

DROP TABLE IF EXISTS `textblocks`;

DROP TABLE IF EXISTS `facilities`;

DROP TABLE IF EXISTS `facility_status`;

DROP TABLE IF EXISTS `facility_types`;

DROP TABLE IF EXISTS `incident_types`;

DROP TABLE IF EXISTS `log`;

DROP TABLE IF EXISTS `regions`;

DROP TABLE IF EXISTS `units`;

DROP TABLE IF EXISTS `tickets`;

DROP TABLE IF EXISTS `unit_types`;

DROP TABLE IF EXISTS `unit_status`;

DROP TABLE IF EXISTS `users`;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
