SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;


INSERT INTO `hints` (`tag`, `hint`) VALUES
('_added', 'Timestamp \"New\" saved.'),
('_api_setting', 'Settings'),
('_api_encoding', 'Addresses'),
('_api_status', 'Status'),
('_api_action', 'Receipt'),
('_api_message_text', 'Text'),
('_api_user_id', 'User whose password used to authenticate and whose name is displayed in log entries.'),
('_api_hosts', 'Receiving allowed from this addresses. If the field is empty, no messages will be accepted from the application interface.'),
('_api_destination_host', 'Messages sent to this address.'),
('_api_phone_host', 'Optional destination to the messages for mobile phones to be sent. For example, Via a script to reach SMS or app alarm services on the Internet. If it is not configured, for cellphones the same destination is used as for the other services.'),
('_api_destination_password', 'API host password'),
('_api_connection_test_configuration', 'Configuration of the periodic connection test of the application interface. Time values, in seconds, values from 10 to 600 [repeat period, outgoing only if not connected],[repeat period, outgoing only if connected],[string for &code=CONNECTION_TEST],[string to select incoming messages via &source=success green ],[String to select incoming messages via &source=error red],[string to assign incoming messages via &destination=phone to the optional application interface for mobile phones],[string, Which must be received as a response when the connection test is successful, with an empty parameter, no response is checked]<br>Defaults: 60, 300, CONNECTION_TEST, success, warning, error, phone, HTTP/1.1 200 OK'),
('_api_prefix_phone_encdg', 'API prefix is used to send the subscriber address via the application interface. Example PHONE: +491234567890'),
('_api_prefix_phone_capt', 'Labeling the message paths when sending messages.'),
('_api_prefix_printer_encdg', 'Alarm printers are searched for in unit data in data services with a prefix API prefix and a colon as a separator. Example of printer address: PRINTER:ipp://localhost:631/printers/my_printer'),
('_api_prefix_printer_capt', 'Labeling the message paths when sending messages.'),
('_api_prefix_reporting_channel_1_encdg', 'Subscriber addresses are searched for in the unit data in data services according to the search pattern with a prefix API prefix and a colon as a separator.API prefix is also used to send the subscriber address via the destination parameter of the application interface. Example of subscriber address: TETRA:262000112345678'),
('_api_prefix_reporting_channel_1_capt', 'Labeling the message paths when sending messages.'),
('_api_prefix_reporting_channel_1_regexp', 'Subscriber addresses are searched for in the unit data in data services according to the search pattern with a prefix API prefix and a colon as a separator.API prefix is also used to send the subscriber address via the destination parameter of the application interface. Example of subscriber address: TETRA:262000112345678'),
('_api_prefix_reporting_channel_2_encdg', 'Subscriber addresses are searched for in the unit data in data services according to the search pattern with a prefix API prefix and a colon as a separator.API prefix is also used to send the subscriber address via the destination parameter of the application interface. Example of subscriber address: FMS:A1B2C3D4'),
('_api_prefix_reporting_channel_2_capt', 'Labeling the message paths when sending messages.'),
('_api_prefix_reporting_channel_2_regexp', 'Subscriber addresses are searched for in the unit data in data services according to the search pattern with a prefix API prefix and a colon as a separator.API prefix is also used to send the subscriber address via the destination parameter of the application interface. Example of subscriber address: FMS:A1B2C3D4'),
('_api_prefix_reporting_channel_3_encdg', 'Subscriber addresses are searched for in the unit data in data services according to the search pattern with a prefix API prefix and a colon as a separator.API prefix is also used to send the subscriber address via the destination parameter of the application interface. Example of subscriber address: ZVEI:12345'),
('_api_prefix_reporting_channel_3_capt', 'Labeling the message paths when sending messages.'),
('_api_prefix_reporting_channel_3_regexp', 'Subscriber addresses are searched for in the unit data in data services according to the search pattern with a prefix API prefix and a colon as a separator.API prefix is also used to send the subscriber address via the destination parameter of the application interface. Example of subscriber address: ZVEI:12345'),
('_api_prefix_reporting_channel_4_encdg', 'Subscriber addresses are searched for in the unit data in data services according to the search pattern with a prefix API prefix and a colon as a separator.API prefix is also used to send the subscriber address via the destination parameter of the application interface. Example of subscriber address: POCSAG:1234567A'),
('_api_prefix_reporting_channel_4_capt', 'Labeling the message paths when sending messages.'),
('_api_prefix_reporting_channel_4_regexp', 'Subscriber addresses are searched for in the unit data in data services according to the search pattern with a prefix API prefix and a colon as a separator.API prefix is also used to send the subscriber address via the destination parameter of the application interface. Example of subscriber address: POCSAG:1234567A'),
('_api_prefix_reporting_channel_5_encdg', 'Subscriber addresses are searched for in the unit data in data services according to the search pattern with a prefix API prefix and a colon as a separator.API prefix is also used to send the subscriber address via the destination parameter of the application interface. Example of subscriber address: TETRA:262000112345678'),
('_api_prefix_reporting_channel_5_capt', 'Labeling the message paths when sending messages.'),
('_api_prefix_reporting_channel_5_regexp', 'Subscriber addresses are searched for in the unit data in data services according to the search pattern with a prefix API prefix and a colon as a separator.API prefix is also used to send the subscriber address via the destination parameter of the application interface. Example of subscriber address: TETRA:262000112345678'),
('_api_evaluate_unknown_unit_emergency_encdg', 'Emergency call from unknown unit - [emergency call high 0 = no, 1 = yes],[emergency call low 0 = no, 1 = yes],[period of time in which position data of unknown unit are received after an emergency call, in minutes]. Default: 1, 0, 5'),
('_api_disp_encdg', 'API-Code for Dispatched inbound and outbound messages. Example: &code=DISPATCHED'),
('_api_resp_encdg', 'RespondingAPI-Code for Dispatched inbound and outbound messages. Example: &code=DISPATCHED'),
('_api_onsc_encdg', 'API-Code for On scene inbound and outbound messages. Example: &code=ON_SCENE'),
('_api_fcen_encdg', 'API-Code for Facility enroute inbound and outbound messages. Example: &code=FACILITY_ENROUTE'),
('_api_fcar_encdg', 'API-Code for Facility arrived inbound and outbound messages. Example: &code=FACILITY_ARRIVED'),
('_api_clr_encdg', 'API-Code for Clear inbound and outbound messages. Example: &code=CLEAR'),
('_api_quat_encdg', 'API-Code for Quater inbound and outbound messages. Example: &code=TO_QUATER'),
('_api_off_duty_encdg', 'API-Code for Off duty inbound and outbound messages. Example: &code=NO_SERVICE'),
('_api_callreq_encdg', 'API-Code for Call request inbound  messages. Example: &code=CALL_REQUEST'),
('_api_manackn_encdg', 'API-Code for Manual acknowledge inbound  messages. Example: &code=MANUAL_ACKNOWLEDGE'),
('_api_emgcy_lo_encdg', 'API-Code for Urgend call request inbound  messages. Example: &code=EMERGENCY_CALL_LOW'),
('_api_emgcy_hi_encdg', 'API-Code for Emergency request inbound  messages. Example: &code=EMERGENCY_CALL_HIGH'),
('_api_ptt_prefix_encdg', 'Prefix for code other than subscriber address for PTT. Example: OPTA: NWRE MUS RTW 1'),
('_api_ptt_encdg', 'API-Code for Push to Talk inbound  messages. Example: &code=PTT'),
('_api_ptt_release_encdg', 'API-Code for Push to Talk release inbound  messages. Example: &code=PTT_RELEASE'),
('_api_ptt_display_encdg', 'Show PTT in head of page, in tenths of a second - [dispay time], [fade out after display]. Values: 1 - 999.<br>Default: 20, 60'),
('_api_log_max_display_setng', 'Display duration of edited messages and call list in minutes.<br>Default: 30'),
('_api_log_max_age_setng', 'Period after the data in the API log are cleared in minutes (60 to 10080, 0 = off).<br>Recommended value: 1440'),
('_api_login_logout_setng', 'API-Code for outgoing message at logon and logoff (Not for user-level guest). Parameter: source=[user-id], destination=[IP address of the workplace], text=[username]. Example: localhost:3142?password=743894a0e4a801fc3&source=2&destination=127.0.0.1&code=LOGIN&text=admin<br>Default: LOGIN, LOGOUT'),
('_api_subscr_unsubscr_setng', 'API code when the evaluation using the units-status off or is turned on - [subscribe], [unsubscribe]<br>Default: SUBSCRIBE, UNSUBSCRIBE'),
('_api_current_radio_encdg', 'API code for incoming message when you change the radio circuit. Only showing call sign of the selected radio circuit in the page header. Parameter: source=[Name de radio circuit, as in the destination parameter PTT message, show all (default) with source = all], destination=[User-ID]. Example: localhost/OpenTacticalDispatcher/api.php?password=743894a0e4a801fc3&source=all&destination=2&code=RADIO<br>Default: RADIO'),
('_api_private_call_encdg', 'API-Code to request individual call. E.g. According to the call request as an alternative to the speech request. Destination parameter contains the participant address. Otherwise the protocol development is the same as when a user logs on and off.'),
('_api_batch_start_stop_setng', 'API-Code parameter for batch-start and batch-stop. Example: &code=BATCH_START'),
('_api_log_encdg', 'API-Code parameter for incoming log-message from aplication interface. Example: &code=LOG'),
('_api_errlog_encdg', 'API-Code parameter for incoming errorlog-message from aplication interface. Example: &code=ERROR'),
('_api_message_encdg', 'API-Code parameter for incoming text-message. Example: &code=MESSAGE'),
('_api_position_encdg', 'API-Code parameter for incoming position-report and outgoing for position-report request. Example: &code=POSITION'),
('_api_email_smtp_host', 'SMTP-Server for Email. Information on protocol, encryption and port are optional. In \"smtps://\" or \"tls://\", the connection only scrambled up, "smtp://\" in or without will only set up a secure connection when the server offers this. Ex.: smtps://mail.example.com:25. In the case of potentially unstable Internet connection, it is advisable to leave the infeed to a local smpt server, e.g. postfix (Unix / Linux) or h-Mailserver (Windows).'),
('_api_email_smtp_authentication', 'Authentification for SMTP-server - [Username],[Password]'),
('_api_email_from', 'Email FROM - [fromaddress],[fromname (optional)]'),
('_api_email_cc', 'Email CC - [ccaddress (optional)], [ccname (optional)]'),
('_api_email_bcc', 'Email BCC - [bccaddress (optional)], [bccname (optional)]'),
('_api_email_reply_to', 'Email REPLY TO - [replytoaddress (optional)],[replytoname (optional)]'),
('_api_default_subject_setng', 'Create default subject (E.g. E-Mail) - [Dispatch message], [To units], [To facilities], [To users]'),
('_api_dispatch_text_setng', 'Create dispatch message from ticket-data (E.g. E-Mail). The letter identifies the text field from which the text is taken, the first digit the first character, and the second digit the last character from the respective text field. Meaning of the letters: A Actions, B Incident location (in UPPERCASE on facility), C Priority, D Incident type, E Written, F Editet, G Reported by, H Phone, I Status, J Incident location, K Synopsis, L Disposition, M Position, N Incident name, O ==========, S Run start and end, T Facility, U Units, V Scheduled. Default: N0,99; E0,99; G0,99; H0,99; O0,99; J0,250; T0,99; D0,99; K0,99; L0,99; O0,99; U0,99;'),
('_api_dispatch_shorttext_setng', 'Create shortened dispatch message from ticket-data (E.g. Short Message Service). The letter identifies the text field from which the text is taken, the first digit the first character, and the second digit the last character from the respective text field. Meaning of the letters: A Actions, B Incident location (in UPPERCASE on facility), C Priority, D Incident type, E Written, F Editet, G Reported by, H Phone, I Status, J Incident location, K Synopsis, L Disposition, M Position, N Incident name, O ==========, S Run start and end, T Facility, U Units, V Scheduled, Z max. Chars. Default: T0,25; B0,39; K0,35; D0,20; N0,10; Z0,109;'),
('_loca', 'Location - type in location in fields or use *Located at Facility* menu below'),
('_callback', 'Phone number for callback. The characters *#+-/0123456789 are permitted. Numbers can be specified separated by comma. When selecting the reporter from the selection field, telephone numbers are automatically adopted.'),
('_copie_or_save_and_copy', 'Copy such as Save and copy via side dropdown-list. Not possible for units if this is in an assignment.'),
('_incident_type', 'Incident  nature or Type - Available types are set in in_types table in the configuration'),
('_prio', 'Incident priority - Normal, Medium or High. Affects order and coloring of incidents on Situation display. Preselected by incident-type at ticket add.'),
('_proto', 'Incident Protocol - this will show automatically if a protocol is set for the Incident Enter the configuration'),
('_regions', 'Sets groups that Incident is allocated to - click + to expand, - to collapse'),
('_save_and_copy', 'Save and copy via side dropdown-list.'),
('_synop', 'Synopsis - Details about the incident, ensure as much detail as possible is completed'),
('_caller', 'Caller reporting the incident. Stored phone numbers are automatically transferred to the Callback number field.'),
('_name', 'Incident Name - Partially completed and prepend or append incident ID depending on setting. Enter an easily identifiable name.'),
('_booked', 'Scheduled Date. Must be set if incident Status is *Scheduled*. Sets date and time for a future booked Incident, mainly used for non immediate patient transport. Click on Radio button to show date fiel'),
('_facy', 'Use the dropdown menu to select the Facility where the incident is located'),
('_facy_on_scene', 'Use the dropdown menu to select the facility where the transport starts'),
('_facy_rec', 'Use the dropdown menu to select the facility where persons from the Incident will be received'),
('_start', 'Timestamp \"New\" clicked. Defaults to current date and time or edit by clicking padlock icon to enable date & time fields'),
('_status', 'Incident  Status - Open or Closed or set to Scheduled for future booked calls'),
('_end', 'Run-end - incident  end time. When incident is closed, click on radio button which will enable date & time fields'),
('_cmnts', 'Additional comments about incident, special events, request external forces, information to third parties, particularly closing it or equivalent.'),
('_cmnts_ass', 'Additional comments about disposition, e.g. patient name'),
('_coords', 'Incident Lat/Lng - set by clicking on the map for the location or by selecting location with the address fields.'),
('_asof', 'Date/time of most recent incident data update'),
('_SevSeverity', 'Severity'),
('_SevNormal', 'Normal'),
('_SevMedium', 'Medium'),
('_SevHigh', 'High'),
('_def_lat', 'Map center default lattitude'),
('_def_lng', 'Map center default longitude'),
('_def_zoom', 'Map default zoom'),
('_FacName', 'Facility Name, e.g. fill in with Name/index where is the label in the list and on the marker'),
('_FacHand', 'Handle, e.g. local rules, local abbreviated name for the facility'),
('_FacIcon', 'HA 3-letter value to be used in the map icon'),
('_FacType', 'Facility type, select from pulldown menu'),
('_FacStat', 'Facility status, select from pulldown menu'),
('_FacLoca', 'Location, e.g. type in location in fields or click location on map'),
('_FacCity', 'City, default city set in configuration. Type in City if required.'),
('_FacObId', 'Used to generate ticket from message with facility-id.'),
('_FacDesc', 'Facility description, e.g. additional details about facility'),
('_FacCapa', 'Facilty capability, e.g. ER, Cells, Medical distribution'),
('_FacConN', 'Facility main contact name'),
('_FacConE', 'Facility contact email address. Multiple email addresses can be entered separated by commas. Ex .: my_first_address@example.com, my_second_address@example.com');

INSERT INTO `hints` (`tag`, `hint`) VALUES
('_FacConP', 'Facility contact phone number, e.g. main contact phone number'),
('_FacSecC', 'Facility security contact'),
('_FacSecE', 'Facility security contact email. Multiple email addresses can be entered separated by commas. Ex .: my_first_address@example.com, my_second_address@example.com'),
('_FacSecP', 'Facility security contact phone number'),
('_FacOpen', 'Facility opening hours, e.g. 24x7x365, 8 to 5 mo to sat etc.'),
('_FacAcce', 'Facility access rules, e.g. enter by main entrance, enter by ER entrance, call first etc'),
('_FacDirectDial1', 'Facility contact primary direct dial number'),
('_FacDirectDial2', 'Facility contact secondary direct dial number'),
('_FacRemo', 'Delete Facility from system');

INSERT INTO `hints` (`tag`, `hint`) VALUES
('_reports_dispatch_message', 'If selected units have data targets, the print preview is displayed on the next but one page.'),
('_reports_period', 'Period in which the beginning of operations, the feed end or the diary entry has occurred.'),
('_reports_function', 'Addiction either in operations or operational diary and refer associated tables. For example, can be filtered listings in use diary even after the guard for the specified unit without the guard occurs in the entry of the use diary.'),
('_reports_filter', 'Entries in the categories communication, status and settings can be hidden when the log is displayed.'),
('_reports_text_query', 'Search in the fields of use, callback number, Reporter, emergency situation, transporting Start, transportation destination remarks.'),
('_reports_location', 'Search in the fields of use and transportation start.'),
('_reports_receiving', 'Search in transport target field.'),
('_reports_incident_name', 'Search the incident name field.'),
('_reports_incident_type', 'Filters by using keyword. It displays only use keywords that have been used in operations / in use diary.'),
('_reports_unit', 'Filters by predisposed units. Only units that have been used in operations / in use diary.'),
('_reports_guard_house', 'Filters by the guard the scheduled units. Only showing guards that have been used in operations / in use diary.'),
('_reports_user', 'Filters by users. It displays only users who have saved in operations / in use diary entries.'),
('_reports_status', 'Filters by status of the operation. Get more information on status values that exist in stakes.');

INSERT INTO `hints` (`tag`, `hint`) VALUES
('_ResName', 'Units Name'),
('_ResHand', 'Handle, e.g. locale rules, could be callsign or badge number, generally for radio comms use'),
('_ResType', 'Units type, select from pulldown menu'),
('_ResMobi', 'Units ist mobile unit?'),
('_ResMult', 'Units can usually be dispatched only once. Multi-dispatchable is a unit which can be dispatched simultaneously into several incidents, for example a logistics vehicle, that can get several orders at the same time. A unit whose address data is to be used for message transmission, but which can not be used in incidents, is not dispatchable. For example, A fixed accident assistance center.'),
('_ResStat', 'Units status, select from pulldown menu'),
('_ResGuHo', 'Select facility as guard house. When using the import function, the facilities must be imported before the units!'),
('_ResPhon', 'Phone number. Numbers can be specified separated by comma.'),
('_ResDesc', 'Facility description, e.g. additional details about unit'),
('_ResCapa', 'Units capability, e.g. training, equipment on board etc'),
('_ResConN', 'Units contact name'),
('_ResConV', 'Contact via email to unit. Multiple email addresses can be entered separated by commas. Ex .: my_first_address@example.com, my_second_address@example.com'),
('_ResSMSR', 'This is to send data-service e.g. via private mobile Radio or others. Addresses must be specified separated by commas. Ex.: IPP:ipp://10.44.37.51:631/printers/myprinter, TETRA:xxxyyyyzzzzzzzz<br><br>ATTENTION: When inserting addresses by copy & paste from Office documents, non-printable control characters can be transferred to the database. This can lead to malfunctions, the cause of which is difficult to determine. If necessary, the detour should be via a pure text editor, e.g. taken from the Windows editor, in order to only transfer the address text.'),
('_ResRepChan', 'Link data from other unit to copy.'),
('_ResRemo', 'Delete unit from system, disallowed if unit is assignet to any calls.'),
('_locale', 'language Preference'),
('_lat_lng', 'Lat/lng display: (0) for DDD.ddddd, (1) for DDD MMM SS.ss, (2) for DDD MM.mm'),
('_NO12345', 'incident numbers only'),
('_Label12345', 'your Label precedes the incident number'),
('_YR12345', 'the year, formatted on variable <b>date_format_year_only</b>, precedes the incident number'),
('_inc_name_sep', 'Separator between Lable or Year an number, e.g. dash, slash, space character.'),
('_inc_next_num', 'Next Incident number'),
('_NO#12345', 'Using Database Ticket-Table ID'),					
('_Free_text/NO#12345', 'Manual Incident name with auto-append Database Ticket-Table ID'),
('_NO#12345/Free_text', 'Manual Incident name with auto-prepend Database Ticket-Table ID'),
('_Free_text(add)', 'Manual Incident name'),
('_Free_text(edit)', 'Manual Incident name, editing enabled'),
('_UTM', 'Shows _UTM values in addition to Lat/Long');

INSERT INTO `hints` (`tag`, `hint`) VALUES
('_user_name', 'Login username.'),
('_user_password', 'Login password.'),
('_user_level', 'The user role defines the task and the rights management for each user. More information can be found in the settings of each user role.'),
('_user_email', 'E-mail address via which the user can be informed. Multiple email addresses can be entered separated by commas. Ex .: first_address@example.com, second_address@example.com'),
('_user_remove', 'User login after delete is no longer possible, past activities remain. The option depends on the user role and not possible for the user, which is defined for use by the application interface.');

INSERT INTO `hints` (`tag`, `hint`) VALUES
('AdminPerms', 'To protect master data that should not be affected by changes in the course of the assignment, the change authorization can be restricted to the superadmin. Application-related adjustments, such as Objects with mission-specific properties or units with daily call names can be created by the shift supervisor in two different ways. Either with copying and changes in the respective copy or (only for units) by transferring connection data from the master data units to the application-specific units. In order to show and hide data records in blocks, they can be assigned to an operational category.'),
('auto_dispatch', '[After new ticket automatically: to situation: 0, to dispatch units: 1], [after last unit clear automatically: no action: 0, to edit ticket: 1, to close ticket: 2], [The browsers back button takes you back to the situation page: Off: 0, On: 1]. Default: 1, 1, 1'),
('auto_poll', 'Automatic updating, in tenths of a second - [synchronize with the server], [shortest update interval of the client]. Values: 1 - 99.<br>Default: 10, 50'),
('callboard', 'Call Board - [0, 1, 2 - for none, floating window, fixed frame], [fixed part in pix], [heigh per line in pix], [min. height in pix],  [max. height in pix]<br>Default: 0, 80, 35, 80, 300'),
('closed_interval', 'Interval in minutes - [Closed tickets are visible in Situation], [Cleared dispatches in callboard are able to fade in].<br>Default: 0, 1440'),
('com_action_button_disabled', 'Editing blocked. Release after processing previous messages from the data source. When a status value is accepted again, it is set with a new time. Status values that follow in the deployment process are not reset.'),
('connection test button', 'Trigger a outgoing connection test for all configured application interfaces. In order to receive incoming messages, the sending host must be allowed in the settings.'),
('date_format', 'Format dates according to php function date() variables.'),
('date_format_time_only', 'Format dates according to php function date() variables.'),
('date_format_time_only_clock', 'Format dates according to php function date() variables. Used for display current time"'),
('date_format_date_only', 'Format dates according to php function date() variables.'),
('date_format_date_only_clock', 'Format dates according to php function date() variables. Used for display current date.'),
('date_format_year_only', 'Format dates according to php function date() variables. Used for Incident-names prefix.'),
('db_optimize', 'The records for inserts, feedback, and user settings are reorganized with the OPTIMIZE TABLE function of the database. This is recommended to improve after a long duration of the program to the processing speed of the database.'),
('db_reset', 'At this point, reset the database can be to enter a CAPTCHA. CAUTION: When you reinstall all units objects, inserts, feedback i.a. irrevocably deleted.'),
('deactivate_timeout', 'Deactivate auto-logout.'),
('framesize', 'Minimum size of the top frame in pixels. Default: 115'),
('flag_unit', 'Last updated Unit'),
('flag_ticket', 'Units in the same Ticket'),
('heading_blink', 'Heading blinks for new Infos in Seconds. Off: 0. Blink: 1 to max. 99.'),
('help1', 'This configuration wizard helps to set up the initial settings for a new installation. All configuration parameters adjusted later and other data are added under <b>settings</b>. Under <b>Settings</b> => <b>Database</b> => <b>Reset</b>, the database be reinstalled after a textbased prompt. Following the configuration wizard can be run again.'),
('help2', 'On this page you can specify information about your organization / facility, so that they appear later in the header and in the title bar of each page. This is for example useful if you work with several Intallationen simultaneously. You can also leave these fields blank or can set the default settings. A change is possible at any time later and has no functional significance.'),
('help3', 'The incident-types can be used to categorize the tickets. An protocol and a priority are assigned to each key word, which is applied when the ticket is created. Texts can be used to enter standard texts via a dropdown-list. This allows the working speed to be greatly increased.<br>At this point, it is possible to select whether the default-incident-types and -textblocks are to be installed. These enable a fast configuration of a raw installation to a manageable system and contain components for common standard situations. You can use the preview buttons to display the stored pattern configurations. You can create your own sample configurations by adapting the files <b>./sql/default_incident_types.en-US.csv</b> and <b>./sql/default_textblocks.en-US.csv</b>.<br>The grouping of theincident-types and textblocks is optional. The specified group name must be the same for each entry in the same group. The configuration can be adapted at any time via <b>Configuration</b>, including the subsequent installation of the default-incident-types and -textblocks.'),
('help4', 'On this page you can create your units. The examples below you can customize with your data accordingly. If several units with a similar name are required, it is easiest to create only the first unit and to create all the others with the copying function in the unit master data. Further information can be added in the respective master data of the unit.'),
('help5', 'On this page you can create different categories for your units. The examples below you can customize with your data accordingly. The scale on the previous page units are automatically assigned to the first category. The category setting can be changed in the master data of the unit. Additional categories can also be created later.'),
('help6', 'On this page you can create your objects. The examples below you can customize with your data accordingly. Additional objects can also be created later. The created objects may be added in the respective master data page for more information. The objects have same as the units a category and a status. The object status allows you to show or hide the object at different points in the program. When the objects are created, a category and a status are preset. Changes and additions may be made later in the settings.'),
('help7', 'A user account with administrator privileges is created (User: <b>admin</b> Password: <b>admin</b>). With this account, all settings can be edited and all the functions are used. Additional technical information are displayed that are hidden from users with different permission levels. User accounts with the permission level <b>Administrator</b> should be used only for technical administration. If an administrator wants to actively use the software, it should use a second user account with other permission level. For more information on permission levels of user accounts can be found in the reference texts of the appropriate settings. Below, you can choose whether you want to start the configuration wizard immediately or go to the login page. With the configuration wizard, you can quickly create a workable environment for smaller tasks. For larger tasks, the import functions can be used under <b>Configuration</b>.'),
('hide_booked', 'Booked/scheduled runs do not appear on the situation screen until they are this-many minutes from now. Default: 30'),
('level_0', 'All settings can be edited and all functions can be used. Additional technical information is displayed. The user account should only be used for technical administration. If the same user wants to actively use the software, it should use a second access with other authorization level.'),
('level_1', 'It can be edited and scheduled operations. All relevant within the operational settings can be made. Appearances: create, edit, dispose. Use diary: Read, Add. Units: create, edit, delete. Objects: Create, edit, delete. User administration (operator and guest): See, add, edit, delete.'),
('level_2', 'It can be edited and scheduled operations. Appearances: create, edit, dispose. Use diary: Read, Add. Units: see change status. Objects: see change status. User Management: Edit your own data.'),
('level_3', 'Authorization level for employees observe all procedures, but should not change yourself. For example, for higher level who wants to look into the insert portion in real time. Appearances: see. Use diary: see. Units: see. Objects: see. User Management: Edit your own data.'),
('log_unit_facility', 'Entries that are assigned to a unit and / or an facility are displayed in the respective title for the configured period.'),
('message_all_units', 'Message to all units'),
('message_all_ticket', 'Message to all units in ticket'),
('message_all_tickets', 'Message to all units in tickets'),
('message_all_facilities', 'Message to all facilities'),
('message_all_users', 'Message to all users'),
('not_deletable', 'The entry cannot be deleted because it is being used.'),
('page_caption', 'Page caption - cosmetic'),
('parking_form_data', '[Add ticket - activate the parking function based on the characters entered in the fields of location, callback number or emergency situation, from 1 - 99 in number of characters, 0 = off], [Add ticket - storage period of the parking function, from 1 - 999 in seconds, 0 = off] , [New action - activate the parking function using the characters entered, from 1 - 99 in number of characters, 0 = off], [New action - storage period of the parking function, from 1 - 999 in seconds, 0 = off], [Close ticket - activate parking function based on the characters entered in the field Synopsis or Comments, from 1 - 99 in number of characters, 0 = off], [Close ticket - storage period of the parking function, from 1 - 999 in seconds, 0 = off], [Log - activate the parking function using entered characters, from 1 - 99 in number of characters, 0 = off], [Log - storage period of the parking function, from 1 - 999 in seconds, 0 = off]. Default setting: 10, 90, 10, 90, 10, 90, 10, 90'),
('parked_trigger_chars', 'With the following minimum number of characters entered in this field, all data on this form will be parked'),
('parked_seconds', 'The parking time is in seconds'),
('release_file', 'URL to the file with information about available updates.'),
('reported_by_phone', 'Transfer of the telephone number of the Incident-reporter from the Select-field to the Callback number field. [Facility Direct dialing 1, 1 = Selected], [Facility Direct dialing 2, 1 = Selected], [Facility Security phone, 1 = Selected], [Facility Contact phone, 1 = Selected], [Unit Cellular phone, 1 = Selected] Default: 0, 0, 1, 0, 1'),
('report_last', '[Show last entries in reports, from 5 - 99999 in minutes], [Entries for communication are hidden by default, 1 = Hidden], [Entries for status are hidden by default, 1 = Hidden], [Entries for settings are hidden by default, 1 = Hidden] Default setting: 720, 720, 720, 0, 0, 1'),
('report_log', '[Show last entries in the log, from 5 - 99999 in minutes], [Show last manual entries in the tooltip of the respective unit, 0 to 99999 in minutes, 0 = disabled], [Show last manual entries in the tooltip of the respective object 0 - 99999 in minutes, 0 = disabled], [Entries for communication are hidden by default, 1 = Hidden], [Entries for status are hidden by default, 1 = Hidden], [Entries for settings are hidden by default, 1 = Hidden] Default setting: 720, 1440, 1440, 0, 0, 1'),
('set_api_settings', 'At this point the email outgoing mail server and the behavior of the application interface is configured. The configuration of network printers is done directly in the settings of the respective unit. To send emails from the program the example configuration must be replaced with the login data of an existing e-mail server. The communication of the application interface is HTTP GET requests. A test interface can thus be carried from the address bar of any browser. Here, the information is transported only in the request. The values ​​of query parameters have to be URL encoded. In the corresponding Response only HTTP status code and debugging information are included. The call is made in both directions according to the following scheme (here intercom call to unity) http://localhost:3142?password=743894a0e4a801fc3&source=&destination=TETRA%3A262999912345678&code=FIXTEXT_06&text=You%20can%20speak The optional audio_link parameter can be used to specify a URL for an audio file in the case of phone calls or telephone calls. This link appears in the speech list as an audio player under the respective entry. In code parameters can both state values ​​and the API-codes are transferred for events. The following example transfers the voice request a unit in the dispatchsoftware which is parameter source_regexp this optional and allows you to search in the database on a regular expression: http://localhost/OpenTacticalDispatcher/api.php?password=743894a0e4a801fc3&source=TETRA:262123499995678&source_regexp=TETRA:(262999912345678)|(262.9999.2345678)|(2345678)|(12345678)&destination=262999987654321&code=CALL_REQUEST&text= The next example shows that pressing the talk button in the dispatchsoftware, the parameters destination_alias here is optional and is in the communication overview instead of actual destination address displayed: http://localhost/OpenTacticalDispatcher/api.php?password=743894a0e4a801fc3&source=OPTA:NWFW%20MUS%20%201RTW%20%20%2001&destination=262999987654321&destination_alias=MUS_RD&code=PTT&text= The API code, depending on the transmission direction have different meanings, example: dispatchsoftware => POSITION => unit: triggers position data query, unit => POSITION => dispatchsoftware: includes position data of the unit. The pre-configured delivery password is identical to the password of the gateway user. For more information about configuration can be found in the reference texts for the respective input fields.'),
('set_audio', 'Important events in the program sequence are linked to their own attention tones. Their output is suppressed at user-specified events generally. The individual beeps can sample belongs at this point. If for each event no audio file is configured, the audio output is switched off at the event. A change in the alert tones will not take effect until after reloading the page. For more information about configuration can be found in the reference texts for the respective input fields.'),
('set_captions', 'At this point, the text output of the program are configured. With this function, the linguistic translation of the program is realized. If the labeling of buttons, text boxes, or the like is to be changed, this is possible at this point. Changes at this point are not usually required.'),
('set_facilities_common_status', 'At this point, all facilities can be set to a common state together or in groups. This is e.g. after an import of objects necessary because this (regardless of the displays a status) do not yet have a valid state after import. Furthermore, as can be on this feature the facilities of different venues or hide. For this purpose, this function is also available to the user role admin available.'),
('set_facilities_status_after_import', 'After import, setting facilities status to common value!'),
('set_facilities_category', 'Here you can define the categories of objects. The objects can be sorted in the list according to the category, it takes place in accordance with color display and the name of the unit category will appear in the respective tooltip. An entry can only be deleted if it is not used.'),
('set_facilities_status_value', 'Here you can define the status names for objects. The status values display the objects at different locations can be controlled in the program. An entry can only be deleted if it is not used.'),
('set_fixtexts', 'The pre-configured at this point messages are provided for sending fixed messages to units. Some of these messages are configured as actions in the application interface and for their proper functioning is necessary and can not be deleted if they are in use. Changes at this point are not usually required.'),
('set_hints', 'At this point the reference texts for the individual program functions are configured. With this function, the linguistic translation of the Note texts is realized. Changes at this point are not usually required.'),
('set_incident_names', 'At this point, the assignment of ticket numbers (more precisely, ticket names) is configured. Basically, there are three different possibilities: 1. According to table ID 2. With a counter 3. Input of a free text. Assignment by table ID is preconfigured and the most robust and easiest way. Depending on the configuration, the insert number can also be combined with a freely selectable text when creating the insert. When clicking on New button, a table ID is reserved for the respective user to record the start time. If the ticket is then not saved (opened), this ID remains reserved for the user and will only be used when creating the next ticket (with a new start time). As a result, it may happen that individual ticket numbers are missing, or only later find use and their order is not chronologically related. When assigning the ticket number using a counter, the application number is always continuous. In addition, it is possible to combine the ticket number with the year or a freely selectable character string. It is also possible to reset the ticket number to a specific value. This option should only be used if there is a need, as the ticket number is used to clearly identify the use. The possibility to count the number of created tickets within a period exists under the menu item Reports. The manual assignment of an ticket number by entering a free text (any alphanumeric text can be entered) is suitable when executing tickets of another leader whose ticket number is to be used, e.g. Severe weather operations. Further information on the configuration can be found in the notes for the respective input fields.'),
('set_incident_types', 'With the use of keywords which inserts to be processed can be categorized. Each application keyword is associated with an alarm proposal and a priority that is taken when creating the deployment. The grouping of keywords use is optional. The specified group name must be identical for each entry of the same group.'),
('set_incident_types_default', 'The pre-configured default incident types can be displayed and installed here. The preconfiguration can be adapted at the file <b>./sql/default_incident_types.en-US.csv.</b>'),
('set_settings', 'The pre-configured at this point values are necessary for the proper functioning of the program. Except for the configuration of the page headers changes at this point are usually not required. For more information about configuration can be found in the reference texts for the respective input fields.'),
('set_units_common_status', 'All units that are not dispatched in a ticket can be placed in this location at the same time to the same state value. This is e.g. after an import of units necessary since this after importing (regardless of the displays a status) still do not have a valid status. Des farther can be taken simultaneously from the evaluation order to use the end of all units. For this purpose, this function is also available to the user role admin available.'),
('set_units_status_after_import', 'After import, setting units status to common value! Thus the import of the guards house functions, they must be present beforehand (imported)!'),
('set_units_category', 'Here you can define the categories of units. The units can be sorted in the table on the category, it takes place in accordance with color display and the name of the unit category will appear in the respective tooltip. An entry can only be deleted if it is not used.'),
('set_units_status_value', 'Here you can define the status designations for the availability of units. For each status it can be set whether the disposition in a ticket should be possible or not. A disposition triggered via the communication side is always possible. The current status of the respective unit is not relevant. The pre-configured at this point Status values are necessary for the proper functioning of the application interface and can not be modified or deleted if they are in use. Changes at this point are not usually required. The status label for use progress and answering requests are predefined in program code.'),
('set_textblocks', 'With the text blocks periodic information can be entered into text fields. This leads to an enormous increase in processing speed. For each machining situation there own text modules. The grouping of text blocks is optional. The specified group name must be identical for each entry of the same group.'),
('set_textblocks_default', 'The pre-configured default textblocks can be displayed and installed here. The preconfiguration can be adapted at the file <b>./sql/default_textblocks.en-US.csv</b>.'),
('session_time_limit', 'Minutes of inactivity before logout is forced - [inactivy, 0 to 99 in minutes, 0 = disabled], [warn-period before logout in minutes, must been minor than inactivity]<br>Default: 30, 5'),
('show_hide_password', 'Show or hide password.'),
('sort_units', 'Default sort for Units. 1-handle, 2-type, 3-status, 4-status, dispatched on top.<br>Default: 2'),
('sort_facilities', 'Default sort for Facilities. 1-handle, 2-type, 3-status.<br>Default: 1'),
('sound_code', 'Occasion on which the relevant advisory to play.'),
('sound_file', 'Sound files for alerts (Ex.: ding.ogg), in .ogg, .mp3 or .wav or other format. The sound files must be stored in the folder are "sounds" After changing the sound file, the page must be loaded new, so the browser can play the sound file.'),
('sound_file_alternative', 'Optional sound file for alert in an alternative format. Only needed if one of the browser you are using is having problems with playing the file format of the other sound file. After changing the sound file, the page must be loaded new, so the browser can play the sound file.'),
('title_string', 'If text is entered here it replaces the default title in the top bar.'),
('toggle_day_night', 'Toggle day / night view.'),
('tolerance', 'Minutes to STRIKE update Time.<br>Default: 90'),
('Updates', 'Here the program can be updated over the Internet to a newer version. If newer versions are available, they are displayed with update notes. The update can only be made from one version to the next, it is not possible to skip versions. Close all other applications on the server-computer before performing the update! Usually, the update process takes only a few seconds, depending on the Internet speed. All other users are logged out during the update process. The update process is finished when the info box with the green progress bar disappears again and the display has automatically switched to the situation-site. To avoid malfunctions, all data in the browser cache must also be refreshed. The easiest way is to log the user out once and close the browser. After opening the browser and re-logging in a user, all information in the browser cache should have been refreshed. Before updating, you should back up the database and the program files. An update should not be made immediately before a scheduled use of the program.'),
('Update-hint', 'The update process is finished when the info box with the green progress bar disappears again and the display has automatically switched to the position display. To avoid malfunctions, all data in the browser cache must also be refreshed. The easiest way is to log the user out once and close the browser. After opening the browser and re-logging in a user, all information in the browser cache should have been refreshed.'),
('night_color', 'Background color by night-view, in hex.<br>Default: #C0C0C0'),
('audio_ticket', 'Audio Note after saving a new ticket.'),
('audio_dispatch', 'Audio Note after dispatching one or more units. Alternatively, a spoken audio preserve under the file names new_disposition.ogg and new_disposition.mp3 are included.'),
('audio_call_progression', 'Audio Note after changing the call progress of a unit.'),
('audio_status', 'Audio Note after changing the availability of a unit.'),
('audio_action', 'Audio Note after creating or changing a action.'),
('audio_default', 'Audio Note for any other event.'),
('audio_new_message', 'Audio Note during a new textmessage received. Not for userlevel \"Guest\"'),
('audio_call_request', 'Audio Note during a callrequest received. Not for userlevel \"Guest\"'),
('audio_emergency_low', 'Audio Note during a urgend callrequest received. Not for userlevel \"Guest\"'),
('audio_emergency_high', 'Audio Note during a emergency callrequest received. Not for userlevel \"Guest\"');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
